[[juliaup]]
arch = "aarch64"
git-tree-sha1 = "423d27cb3e95f39844720eaa1d492cf83c8293ee"
os = "macos"

    [[juliaup.download]]
    sha256 = "8510abba354077e1abbdac5d7fe258116929380039d278f9d7694e8d06297b80"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.aarch64-apple-darwin.tar.gz"
[[juliaup]]
arch = "aarch64"
git-tree-sha1 = "0a6fa5f872b4a938b534d9c5e7a42e3464fe26b1"
libc = "glibc"
os = "linux"

    [[juliaup.download]]
    sha256 = "24c163931fc35c4081398eb9619bf338f2072dd7f2563d25565cd69e69fbc767"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.aarch64-linux-gnu.tar.gz"
[[juliaup]]
arch = "aarch64"
git-tree-sha1 = "ad570de9999dc61bc142957cf17f038cfe62bf00"
libc = "musl"
os = "linux"

    [[juliaup.download]]
    sha256 = "7bcf1295e713e771ede334333b8a66c2521d1590b96d800fd390a81f114f6200"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.aarch64-linux-musl.tar.gz"
[[juliaup]]
arch = "i686"
git-tree-sha1 = "76496ed915d2677830ad137f52f11c4e4be744bd"
libc = "glibc"
os = "linux"

    [[juliaup.download]]
    sha256 = "7d7124288e22c32ebbd915a17fb5c2bac4074e650df83da7a6baa772707af9d2"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.i686-linux-gnu.tar.gz"
[[juliaup]]
arch = "x86_64"
git-tree-sha1 = "b7650704fdc4c849ee78e502dfa50d787d4b84af"
os = "macos"

    [[juliaup.download]]
    sha256 = "fcd3c0b137c85de218f33a5c681edd1af4af33fc57cb9be0e8bb8db5a941dbf6"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.x86_64-apple-darwin.tar.gz"
[[juliaup]]
arch = "x86_64"
git-tree-sha1 = "380f7538f11c6ecba00e3b1ea6d7f153ee996cc1"
libc = "glibc"
os = "linux"

    [[juliaup.download]]
    sha256 = "705a4554d7a218a97b4eeb0265707ef2907650e5d6f8da4fcf5bd7994f7f0edd"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.x86_64-linux-gnu.tar.gz"
[[juliaup]]
arch = "x86_64"
git-tree-sha1 = "52c13499594d8d3f134a27d11f57293f8d16a3dd"
libc = "musl"
os = "linux"

    [[juliaup.download]]
    sha256 = "79944177170d12f7269027b9cc6944ef0369e7084c675170ef877786a0c6cd7b"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.x86_64-linux-musl.tar.gz"
[[juliaup]]
arch = "x86_64"
git-tree-sha1 = "4dfe7df8927b10008a12be6b7d5527f55eb2f524"
os = "freebsd"

    [[juliaup.download]]
    sha256 = "5aea601bacbfb72bba8127e4fc73799fbd5bba16a59a2016adfe750d319dec3a"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.x86_64-unknown-freebsd.tar.gz"
[[juliaup]]
arch = "x86_64"
git-tree-sha1 = "eef2f87c65477ef697a6c8cc7af029846cc76940"
os = "windows"

    [[juliaup.download]]
    sha256 = "61162b271960619943a1db4d1f76b5113e9123885bc2799336015c7f11931c8f"
    url = "https://github.com/JuliaBinaryWrappers/juliaup_jll.jl/releases/download/juliaup-v1.18.0+0/juliaup.v1.18.0.x86_64-w64-mingw32.tar.gz"
