# Autogenerated wrapper script for juliaup_jll for x86_64-w64-mingw32
export julia, juliaup

using Libiconv_jll
JLLWrappers.@generate_wrapper_header("juliaup")
JLLWrappers.@declare_executable_product(julia)
JLLWrappers.@declare_executable_product(juliaup)
function __init__()
    JLLWrappers.@generate_init_header(Libiconv_jll)
    JLLWrappers.@init_executable_product(
        julia,
        "bin\\julia.exe",
    )

    JLLWrappers.@init_executable_product(
        juliaup,
        "bin\\juliaup.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
