# Autogenerated wrapper script for juliaup_jll for x86_64-linux-gnu
export julia, juliaup

using Libiconv_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("juliaup")
JLLWrappers.@declare_executable_product(julia)
JLLWrappers.@declare_executable_product(juliaup)
function __init__()
    JLLWrappers.@generate_init_header(Libiconv_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        julia,
        "bin/julia",
    )

    JLLWrappers.@init_executable_product(
        juliaup,
        "bin/juliaup",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
